CAPACITIVE_LOAD_UNIT = "capacitive_load_unit"
OPERATING_CONDITIONS = "operating_conditions"
LEVEL_TYPE_STR = "level_type"
VALS_STR = "vals"
GROUP_STR = "group"
COMPLEX_STR = "complex"
PARAM_INDICATOR_CHAR = "$"
