CELL_RISE = "cell_rise"
CELL_FALL = "cell_fall"
RISE_TRANSITION = "rise_transition"
FALL_TRANSITION = "fall_transition"
VALUES_STRING = "values(\"{}\")"
TIMING = "timings"
PIN = "pins"

INSIDE_LIBRARY_NUM_SPACES = 2
INSIDE_CELL_GROUP_NUM_SPACES = 4
INSIDE_PIN_GROUP_NUM_SPACES = 6
INSIDE_TIMING_GROUP_NUM_SPACES = 8